高廷佑
authorizeleo/taipei-day-trip-website pull request #3
Opened 2021-04-21 07:44 UTC by authorizeleo

http://13.208.107.238:3000/api/attractions?page=0
http://13.208.107.238:3000/api/attractions?page=0&keyword=新北投溫泉區
http://13.208.107.238:3000/api/attraction/100

在麻煩彭彭老師 如果有需要改進的地方
在跟我說 讓我有更多進步的空間
謝謝彭彭老師

2021-04-21 07:51 UTC, cwpeng requested changes
http://13.208.107.238:3000/api/attractions?page=0&keyword=梅庭
應該要有結果，反而
http://13.208.107.238:3000/api/attractions?page=2&keyword=梅庭
不應該有東西。

第一個連結沒有看到任何結果。另外不用額外開 pull request，就直接在同一個 pull request 要求重新 review 就可以了，比較能追蹤留言來回的狀況。

2021-04-21 07:53 UTC, authorizeleo commented
http://13.208.107.238:3000/api/attractions?page=0
第一個是指這個嗎?

2021-04-21 07:57 UTC, cwpeng commented
http://13.208.107.238:3000/api/attractions?page=0&keyword=梅庭

2021-04-21 07:58 UTC, authorizeleo commented
梅庭 沒有那裏面呀

2021-04-21 08:02 UTC, cwpeng commented
請仔細思考使用情境，我在 #general 中寫的。

所以你在 Google 搜尋梅庭，會在第 0 頁看到空的內容，然後點下一頁，才看到梅庭的結果嗎？

2021-04-21 11:00 UTC, authorizeleo commented
http://13.208.107.238:3000/api/attractions?page=0
http://13.208.107.238:3000/api/attractions?page=0&keyword=新北投溫泉區
http://13.208.107.238:3000/api/attraction/100

老師 在麻煩你檢查了
很謝謝你~~

2021-04-21 15:11 UTC, authorizeleo commented
http://13.208.107.238:3000/api/attractions?page=0
http://13.208.107.238:3000/api/attractions?page=0&keyword=新北投溫泉區
http://13.208.107.238:3000/api/attraction/100

老師 在麻煩你檢查了
很謝謝你~~

2021-04-22 00:49 UTC, cwpeng approved these changes
Good. OK.

2021-04-22 01:36 UTC, authorizeleo commented
謝謝老師

2021-04-22 04:27 UTC, cwpeng commented
記得 Merge Pull Request，之後我不會再提醒了哦 ~

2021-04-22 04:33 UTC, authorizeleo commented
老師 我知道
我想說改一下 整個架構 
想讓老師幫我看一下

2021-04-22 06:59 UTC, authorizeleo commented
老師 我在嘗試mvc架構
我的想法是說
把外面的app.py 當成 route
然後在 model 處理資料
然後以後會在 views裡面 再創一個檔案 來 連動畫面

還是老師會有什麼方式比較推薦呢?
剛剛想了很久

2021-04-22 09:56 UTC, cwpeng commented
把檔案資料放進 DB 的程式，建議不要和 Server Route 互動的 Data 程式放在一起。

檔案資料放進 DB 算是一個預先處理的動作，他不是伺服器運作的時候該發生的事情 ~

2021-04-22 16:54 UTC, merged